services:
  php_app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
